name: Run Producer

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-producer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4   # Set up Python environment, the @v4 ensures we use the latest version of the action
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r producer/requirements.txt

      - name: Run producer
        env:
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python producer/producer.py
